docs: cards added
rahulyadav139/palasio-designs-component-library pull request #3
Opened 2022-02-01 17:32 UTC by rahulyadav139

Card component is added.

2022-02-01 19:48 UTC, aiman-ansari requested changes
Everything is good UI looks so good .
Remove extra spaces and in card with ribbon it would look great if you rotate ribbon more in upward direction. Instead of horizontal change it into cross direction.

2022-02-01 20:51 UTC, varun13169 requested changes

2022-02-01 20:51 UTC, varun13169 commented on components/card/card.css
> +  box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;
Parameterize the color

2022-02-01 20:51 UTC, varun13169 commented on components/card/card.css
> +  color: var(--white-color);
Try to give the meaningful color name

2022-02-01 20:51 UTC, varun13169 commented on components/card/card.css
> +  color: var(--white-color);
Same as above.

2022-02-01 20:51 UTC, varun13169 commented on components/card/card.css
> +  border: 1px solid var(--grey-color);
same as above.

2022-02-01 21:40 UTC, ShrutiLakhani commented
1. In the Card with Text (Out of Stock) , you can mention it as Card with Text Overlay. 
2. Ribbon would appear better on top left rather than right.

Just these minor observations, rest everything looks great to me.

2022-02-01 21:58 UTC, manojsarna approved these changes
overall code seems good.

GTM

2022-02-01 21:58 UTC, manojsarna commented on components/card/card.css
> +  box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;
create variables for colors

2022-02-01 21:58 UTC, manojsarna commented on components/card/card.css
> +  background: rgba(255, 255, 255, 0.5);
check this color

2022-02-02 05:12 UTC, rahulyadav139 commented
> Everything is good UI looks so good . Remove extra spaces and in card with ribbon it would look great if you rotate ribbon more in upward direction. Instead of horizontal change it into cross direction.

Thank you for the review. Extra spaces have been removed and for rotating ribbon in the upward direction I will need to restructure both pseudo-element (before and after) and it would be too overwhelming for me. So I am rolling with this design style.

2022-02-02 05:14 UTC, rahulyadav139 commented on components/card/card.css
> +  box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;
creating a variable for this colour.

2022-02-02 05:16 UTC, merged

2022-02-02 11:32 UTC, tarunsankhla commented on components/card/card.css
> +  padding: 0.325rem;
Try not using so much decimal place it will create a confusion

2022-02-02 11:34 UTC, tarunsankhla commented on palasio-design.css
> +@import url('./components/util.css');
Looks great just check the alert icon in mobile view it was getting little oval shape
Rest everything is good